### ISSUE TITLE
Help!How to add git push url for gerrit.

### ISSUE THREAD

**Issue by udhaya10** [FredrikNoren/ungit-gerrit#3]
How to add git push url for gerrit.
I wanna push my code to gerrit i installed the plugin(https://github.com/FredrikNoren/ungit-gerrit)

example : push gerrit HEAD:refs/for/devel

**Comment by FredrikNoren** [comment]
There should be a sidebar to the left with a "push for review" button. If
that's not there the plugin might not be configured properly (maybe it's
the wrong plugin directory?)

**Comment by udhaya10** [comment]
Thanks for the reply.
I can see the button.when i push to gerrit it pushes to a branch name which is same as in my local.
But no mater what branch i am in i will always push my code to devel branch in gerrit.Is there a way to change this push url?

from command line i am achieving this by "git push gerrit HEAD:refs/for/devel"

**Comment by FredrikNoren** [comment]
Hm no there's no way to do that right now, I'd suggest either keeping a
devel branch locally and checking out that before pushing or posting a fix
to the plugin
